name: "Pipeline Revisor de código"

on:
  pull_request:
    # branches:
    #   - main
      # Avalia só os PRs que buscam um merge na main
jobs:
  auditoria-agente:
    runs-on: ubuntu-latest
    # Roda uma VR no ubuntu

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # clona o repositório na VR e pega o log dos commits

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependências da automação
        run: |
          python -m pip install --upgrade pip
          pip install requests pydantic

      - name: Instalar dependências (uv)
        working-directory: ./adk
        run: |
          pip install uv
          uv sync

      - name: Executar Agente Revisor
        # vai para a pasta "adk", onde haverão os scripts de validação.
        working-directory: ./adk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          # temporariamente, utilizando a LLM Mistral para testes

        run: uv run python validador.py
        # o script criar o arquivo diff, contendo as diferenças apresentadas no PR e serializando-as para que o agente possa fazer a análise
